"""run table

Revision ID: 062f640281d7
Revises: dc77818f908b
Create Date: 2022-01-06 16:14:03.596350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062f640281d7'
down_revision = 'dc77818f908b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=140), nullable=True),
    sa.Column('seq_platform', sa.String(length=140), nullable=True),
    sa.Column('PE_SE', sa.String(length=140), nullable=True),
    sa.Column('extension', sa.String(length=140), nullable=True),
    sa.Column('extension_user', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_run_id'), 'run', ['run_id'], unique=True)
    op.create_index(op.f('ix_run_timestamp'), 'run', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_timestamp'), table_name='run')
    op.drop_index(op.f('ix_run_run_id'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
