"""task path

Revision ID: adc3b523d935
Revises: a2430230c29d
Create Date: 2022-01-27 15:49:25.242522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc3b523d935'
down_revision = 'a2430230c29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('path', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'path')
    # ### end Alembic commands ###
